version: "3.7"
services:
  app:
    restart: always
    container_name: app
    build: .
    environment:
      - DEV_ID=hselyceum_ring
      - DEV_KEY=SECRET
      - JWT_SECRET=SECRET
      - HASH_SECRET=SECRET
      - DEBUG=TRUE
      - DOMAIN=localhost
      - SCHOOL_DOMAIN=api-test
    depends_on:
      - mongodb
    volumes: 
      - type: bind
        source: ./owo 
        target: /app/owo
    ports: 
      - "80:80"
  mongodb:
    restart: always
    image: "mongo:latest"
    environment:
      - AUTH=no
    volumes:
      - "mongo:/data/db"
    container_name: mongo
    ports:
        - "27017:27017" # for testing

volumes:
  mongo:
