version: "3"
services:
  app:
    restart: always
    container_name: app
    build: .
    environment:
      - DEV_ID=SECRET
      - DEV_KEY=SECRET
      - JWT_SECRET=SECRET
      - HASH_SECRET=SECRET
      - DEBUG=TRUE
    depends_on:
      - mongodb
  mongodb:
    restart: always
    image: "mongo:latest"
    environment:
      - AUTH=no
    volumes:
      - "mongo:/data/db"
    container_name: mongo
  router:
    restart: always
    image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    container_name: nginx

volumes:
  mongo:
