version: "3.7"
services:
  app:
    restart: always
    container_name: app
    build: .
    volumes: 
      - static:/app/owo/static/
    environment:
      - DEBUG=TRUE
    depends_on:
      - mongodb
  mongodb:
    restart: always
    image: "mongo:latest"
    environment:
      - AUTH=no
    # volumes:
      # - "./mongo:/data/db"
    container_name: mongo
    ports:
        - "27017:27017" # for testing
  router:
    restart: always
    image: "nginx:alpine"
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - static:/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ngapp.conf:/etc/nginx/conf.d/ngapp.conf
    container_name: nginx 

volumes:
  static:
